.\"*****************************************************************************
.\" Copyright 2011 by Thomas E. Dickey                                         *
.\" All Rights Reserved.                                                       *
.\"                                                                            *
.\" Permission to use, copy, modify, and distribute this software and its      *
.\" documentation for any purpose and without fee is hereby granted, provided  *
.\" that the above copyright notice appear in all copies and that both that    *
.\" copyright notice and this permission notice appear in supporting           *
.\" documentation, and that the name of the above listed copyright holder(s)   *
.\" not be used in advertising or publicity pertaining to distribution of the  *
.\" software without specific, written prior permission.                       *
.\"                                                                            *
.\" THE ABOVE LISTED COPYRIGHT HOLDER(S) DISCLAIM ALL WARRANTIES WITH REGARD   *
.\" TO THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND  *
.\" FITNESS, IN NO EVENT SHALL THE ABOVE LISTED COPYRIGHT HOLDER(S) BE LIABLE  *
.\" FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES          *
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN      *
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR *
.\" IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.                *
.\"*****************************************************************************
.\" $Id: tctest.1,v 1.4 2011/08/05 09:05:20 tom Exp $
.TH TCTEST 1
.SH NAME
\fBtctest\fP \- termcap library checker
.SH SYNOPSIS
\fBtctest\fP\fI [options] [file-specifications]\fP
.SH DESCRIPTION
\fBtctest\fP exercises the termcap library (or emulation of termcap)
with which it is linked.
It provides several command-line options,
making it simple to construct test-cases to compare implementations
of termcap.
.SH OPTIONS
After processing options,
\fBtctest\fP uses any command-line parameters as the names of
terminal descriptions to process.
If no command-line parameters are given,
\fBtctest\fP tries the \fBTERM\fP environment variable.
If that is not set, the program uses the \fBdumb\fP terminal description.
.PP
The termcap library function
\fBtgetent\fP locates the termcap file,
looking at the \fBTERMCAP\fP environment variable (or \fB/etc/termcap\fP).
\fBtctest\fP manipulates this environment variable,
allowing one to use alternate terminal databases.
.PP
Some of the options provide only summary behavior.
The most useful output from \fBtctest\fP is in \fItermcap\fP
format, with one capability per line.
It is noted that the extra whitespace would be poorly handled
by some termcap implementations, counting toward the 1023 byte
limit on an entry's size.
The reason for listing it in this way is to provide easy comparison.
.PP
These are the options:
.TP
\fB\-a\fP
show capabilities for all names in termcap file.
This overrides the \fB\-b\fP option.
.TP
\fB\-b\fP
use brute-force to find all capabilities, e.g., for the names given on
the command-line.
If the \fB\-b\fP option is not specified,
\fBtctest\fP uses the names from a built-in table of termcap names
chosen to correspond to terminfo capability names.
.TP
\fB\-e\fP
use $TERMCAP variable if it exists.
If this option is not set,
\fBtctest\fP unsets the \fBTERMCAP\fP environment variable.
.TP
\fB\-f NAME\fP
use this termcap file.
\fBtctest\fP sets the \fBTERMCAP\fP environment variable to the
file's absolute path.
.TP
\fB\-l\fP
list names and aliases in termcap file.
.TP
\fB\-o NAME\fP
redirect output (the reformatted input) to this file.
By default that goes to the standard output.
If this option is used, verbose and summary reports are written
to the standard output instead of the standard error,
to allow separating them from error messages that may be written
by the termcap library.
.TP
\fB\-s\fP
show a summary report.
.TP
\fB\-v\fP
verbose (prints names to stderr to track tgetent calls).
This is useful in conjunction with \fB\-a\fP,
e.g., to help pinpoint places where \fBtgetent\fP reports
that a terminal entry is too large.
Repeat the option to get more detail.
.TP
\fB\-w\fP
check the result from \fBtgetent\fP and \fBtgetstr\fP,
printing warnings to the standard error.
.TP
\fB\-V\fP
print the program version and exit
.SH SEE ALSO
.PP
.BR tgetent (3)
documentation for ncurses highlights the differences.
This is a starting point;
although the original BSD source code is recommended reading as well.
.PP
.BR ncurses (3)
is a terminfo-based library,
which provides a termcap interface.
Normally it ignores the \fBTERMCAP\fP variable,
but it can be configured to provide a more accurate emulation of the
termcap library, e.g., loading the terminal entries base on \fBTERMCAP\fP.
.SH AUTHOR
.PP
Thomas Dickey <dickey@invisible-island.net>.
